name: recipe_app
description: A new Flutter project.


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  bloc_test: ^9.1.4
  cupertino_icons: ^1.0.2
  envied: ^0.3.0+3
  equatable: ^2.0.5
  google_fonts: ^4.0.4
  flutter_bloc: ^8.1.3
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^1.1.5
  font_awesome_flutter: ^10.4.0
  http: ^1.1.0
  intl: ^0.18.1
  kiwi: ^4.1.0
  mockito: ^5.4.2
  ruqe: ^1.3.5
  shared_preferences: ^2.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  envied_generator: ^0.3.0
  flutter_lints: ^2.0.0
  kiwi_generator: ^4.1.0



flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/pngs/
    - assets/svgs/
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  

  
  
